<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Opentalent\\Populate\\Command\\ClearDbCommand' => $typo3InstallDir . 'typo3conf/ext/populate/Classes/Command/ClearDbCommand.php',
    'Opentalent\\Populate\\Command\\PopulateCommand' => $typo3InstallDir . 'typo3conf/ext/populate/Classes/Command/PopulateCommand.php',
    'Opentalent\\Populate\\Controller\\SiteController' => $typo3InstallDir . 'typo3conf/ext/populate/Classes/Controller/SiteController.php',
    'Opentalent\\Websites\\Controller\\ActionController' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Controller/ActionController.php',
    'Opentalent\\Websites\\Exception\\InvalidWebsiteConfigurationException' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Exception/InvalidWebsiteConfigurationException.php',
    'Opentalent\\Websites\\Exception\\NoSuchRecordException' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Exception/NoSuchRecordException.php',
    'Opentalent\\Websites\\Exception\\NoSuchWebsiteException' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Exception/NoSuchWebsiteException.php',
    'Opentalent\\Websites\\Utility\\RouteNormalizer' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Utility/RouteNormalizer.php',
    'Opentalent\\Websites\\Website\\ExtendedPageRepository' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Website/ExtendedPageRepository.php',
    'Opentalent\\Websites\\Website\\WebsiteRepository' => $typo3InstallDir . 'typo3conf/ext/websites/Classes/Website/WebsiteRepository.php',
);
